name: Deploy to Prod

on:
  push:
    branches:
      - master
      - feature/**

jobs:
  docker-build-and-push:
    uses: ./.github/workflows/.reusable-docker-build-and-push.yml

  deploy-to-prod:
    needs: [docker-build-and-push]
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy
        # Database connection var used in quotes because without them only part of connection string will be used
        run: |
            helmfile apply --suppress-diff --namespace ${{ secrets.INNER_CIRCLE_PROD_NAMESPACE }} -f Api/ci/helmfile.yaml \
            --state-values-set image.tag=sha-${{ github.sha }} \
            --state-values-set ingress.hostname=${{ secrets.INNER_CIRCLE_PROD_HOSTNAME }} \
            --state-values-set extraSecretEnvVars.ConnectionStrings__DefaultConnection="${{ secrets.INNER_CIRCLE_PROD_EMPLOYEES_DB_CONNECTION_STRING }}" \
            --state-values-set extraSecretEnvVars.AuthenticationOptions__PublicSigningKey=${{ secrets.INNER_CIRCLE_PROD_PUBLIC_SIGNING_KEY }} \
            --state-values-set extraSecretEnvVars.AuthenticationOptions__PrivateSigningKey=${{ secrets.INNER_CIRCLE_PROD_PRIVATE_SIGNING_KEY }} > /dev/null 2>&1

  run-e2e-tests:
    uses: ./.github/workflows/.reusable-e2e-tests-against-prod.yml
    needs: [deploy-to-prod]
    secrets: inherit
